/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as CardRouteImport } from './routes/card'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as CaptureIndexRouteImport } from './routes/capture.index'
import { Route as CaptureCardRouteImport } from './routes/capture.card'
import { Route as CaptureQrRouteImport } from './routes/capture.qr'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureIndexRoute = CaptureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaptureRoute,
} as any)
const CaptureCardRoute = CaptureCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => CaptureRoute,
} as any)
const CaptureQrRoute = CaptureQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => CaptureRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRouteWithChildren
  '/card': typeof CardRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/capture/card': typeof CaptureCardRoute
  '/capture/qr': typeof CaptureQrRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/capture/': typeof CaptureIndexRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/capture/card': typeof CaptureCardRoute
  '/capture/qr': typeof CaptureQrRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/capture': typeof CaptureIndexRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRouteWithChildren
  '/card': typeof CardRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/capture/card': typeof CaptureCardRoute
  '/capture/qr': typeof CaptureQrRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/capture/': typeof CaptureIndexRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/card'
    | '/profile'
    | '/schedule'
    | '/capture/card'
    | '/capture/qr'
    | '/leads/$leadId'
    | '/capture/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/profile'
    | '/schedule'
    | '/capture/card'
    | '/capture/qr'
    | '/leads/$leadId'
    | '/capture'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/card'
    | '/profile'
    | '/schedule'
    | '/capture/card'
    | '/capture/qr'
    | '/leads/$leadId'
    | '/capture/'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRouteWithChildren
  CardRoute: typeof CardRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/': {
      id: '/capture/'
      path: '/'
      fullPath: '/capture/'
      preLoaderRoute: typeof CaptureIndexRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/capture/card': {
      id: '/capture/card'
      path: '/card'
      fullPath: '/capture/card'
      preLoaderRoute: typeof CaptureCardRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/capture/qr': {
      id: '/capture/qr'
      path: '/qr'
      fullPath: '/capture/qr'
      preLoaderRoute: typeof CaptureQrRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaptureRouteChildren {
  CaptureCardRoute: typeof CaptureCardRoute
  CaptureQrRoute: typeof CaptureQrRoute
  CaptureIndexRoute: typeof CaptureIndexRoute
}

const CaptureRouteChildren: CaptureRouteChildren = {
  CaptureCardRoute: CaptureCardRoute,
  CaptureQrRoute: CaptureQrRoute,
  CaptureIndexRoute: CaptureIndexRoute,
}

const CaptureRouteWithChildren =
  CaptureRoute._addFileChildren(CaptureRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRouteWithChildren,
  CardRoute: CardRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
