/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as CardRouteImport } from './routes/card'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminEventRouteImport } from './routes/admin.event'
import { Route as AdminFollowupsRouteImport } from './routes/admin.followups'
import { Route as AdminInviteRouteImport } from './routes/admin.invite'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminReportRouteImport } from './routes/admin.report'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as CaptureIndexRouteImport } from './routes/capture.index'
import { Route as CaptureCardRouteImport } from './routes/capture.card'
import { Route as CaptureQrRouteImport } from './routes/capture.qr'
import { Route as EShareTokenRouteImport } from './routes/e.$shareToken'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as AdminClientsUserIdRouteImport } from './routes/admin.clients.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventRoute = AdminEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFollowupsRoute = AdminFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const CaptureIndexRoute = CaptureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaptureRoute,
} as any)
const CaptureCardRoute = CaptureCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => CaptureRoute,
} as any)
const CaptureQrRoute = CaptureQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => CaptureRoute,
} as any)
const EShareTokenRoute = EShareTokenRouteImport.update({
  id: '/e/$shareToken',
  path: '/e/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsUserIdRoute = AdminClientsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/capture': typeof CaptureRouteWithChildren
  '/card': typeof CardRoute
  '/join': typeof JoinRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/event': typeof AdminEventRoute
  '/admin/followups': typeof AdminFollowupsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/staff': typeof AdminStaffRoute
  '/capture/card': typeof CaptureCardRoute
  '/capture/qr': typeof CaptureQrRoute
  '/e/$shareToken': typeof EShareTokenRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/admin/': typeof AdminIndexRoute
  '/capture/': typeof CaptureIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card': typeof CardRoute
  '/join': typeof JoinRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/event': typeof AdminEventRoute
  '/admin/followups': typeof AdminFollowupsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/staff': typeof AdminStaffRoute
  '/capture/card': typeof CaptureCardRoute
  '/capture/qr': typeof CaptureQrRoute
  '/e/$shareToken': typeof EShareTokenRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/admin': typeof AdminIndexRoute
  '/capture': typeof CaptureIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/capture': typeof CaptureRouteWithChildren
  '/card': typeof CardRoute
  '/join': typeof JoinRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/event': typeof AdminEventRoute
  '/admin/followups': typeof AdminFollowupsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/staff': typeof AdminStaffRoute
  '/capture/card': typeof CaptureCardRoute
  '/capture/qr': typeof CaptureQrRoute
  '/e/$shareToken': typeof EShareTokenRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/admin/': typeof AdminIndexRoute
  '/capture/': typeof CaptureIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/admin/clients/$userId': typeof AdminClientsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/capture'
    | '/card'
    | '/join'
    | '/profile'
    | '/schedule'
    | '/admin/clients'
    | '/admin/event'
    | '/admin/followups'
    | '/admin/invite'
    | '/admin/leads'
    | '/admin/report'
    | '/admin/staff'
    | '/capture/card'
    | '/capture/qr'
    | '/e/$shareToken'
    | '/leads/$leadId'
    | '/admin/'
    | '/capture/'
    | '/leads/'
    | '/admin/clients/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card'
    | '/join'
    | '/profile'
    | '/schedule'
    | '/admin/clients'
    | '/admin/event'
    | '/admin/followups'
    | '/admin/invite'
    | '/admin/leads'
    | '/admin/report'
    | '/admin/staff'
    | '/capture/card'
    | '/capture/qr'
    | '/e/$shareToken'
    | '/leads/$leadId'
    | '/admin'
    | '/capture'
    | '/leads'
    | '/admin/clients/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/capture'
    | '/card'
    | '/join'
    | '/profile'
    | '/schedule'
    | '/admin/clients'
    | '/admin/event'
    | '/admin/followups'
    | '/admin/invite'
    | '/admin/leads'
    | '/admin/report'
    | '/admin/staff'
    | '/capture/card'
    | '/capture/qr'
    | '/e/$shareToken'
    | '/leads/$leadId'
    | '/admin/'
    | '/capture/'
    | '/leads/'
    | '/admin/clients/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaptureRoute: typeof CaptureRouteWithChildren
  CardRoute: typeof CardRoute
  JoinRoute: typeof JoinRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  EShareTokenRoute: typeof EShareTokenRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event': {
      id: '/admin/event'
      path: '/event'
      fullPath: '/admin/event'
      preLoaderRoute: typeof AdminEventRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/followups': {
      id: '/admin/followups'
      path: '/followups'
      fullPath: '/admin/followups'
      preLoaderRoute: typeof AdminFollowupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/capture/': {
      id: '/capture/'
      path: '/'
      fullPath: '/capture/'
      preLoaderRoute: typeof CaptureIndexRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/capture/card': {
      id: '/capture/card'
      path: '/card'
      fullPath: '/capture/card'
      preLoaderRoute: typeof CaptureCardRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/capture/qr': {
      id: '/capture/qr'
      path: '/qr'
      fullPath: '/capture/qr'
      preLoaderRoute: typeof CaptureQrRouteImport
      parentRoute: typeof CaptureRoute
    }
    '/e/$shareToken': {
      id: '/e/$shareToken'
      path: '/e/$shareToken'
      fullPath: '/e/$shareToken'
      preLoaderRoute: typeof EShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/$userId': {
      id: '/admin/clients/$userId'
      path: '/$userId'
      fullPath: '/admin/clients/$userId'
      preLoaderRoute: typeof AdminClientsUserIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsUserIdRoute: typeof AdminClientsUserIdRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsUserIdRoute: AdminClientsUserIdRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminEventRoute: typeof AdminEventRoute
  AdminFollowupsRoute: typeof AdminFollowupsRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminReportRoute: typeof AdminReportRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminEventRoute: AdminEventRoute,
  AdminFollowupsRoute: AdminFollowupsRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminReportRoute: AdminReportRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CaptureRouteChildren {
  CaptureCardRoute: typeof CaptureCardRoute
  CaptureQrRoute: typeof CaptureQrRoute
  CaptureIndexRoute: typeof CaptureIndexRoute
}

const CaptureRouteChildren: CaptureRouteChildren = {
  CaptureCardRoute: CaptureCardRoute,
  CaptureQrRoute: CaptureQrRoute,
  CaptureIndexRoute: CaptureIndexRoute,
}

const CaptureRouteWithChildren =
  CaptureRoute._addFileChildren(CaptureRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CaptureRoute: CaptureRouteWithChildren,
  CardRoute: CardRoute,
  JoinRoute: JoinRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  EShareTokenRoute: EShareTokenRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
